# Generated by Django 2.1.2 on 2018-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
