# Generated by Django 2.1.2 on 2018-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firecast', '0002_podcast_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
